version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - local
    ports:
      - 5432:5432

networks:
  local:
    driver: bridge
